module.exports = [
    'Automobile Parts & Accessories',
    'Cable & Electrical Goods',
    'Cement',
    'Chemical',
    'Close - End Mutual Fund',
    'Commercial Banks',
    'Engineering',
    'Fertilizer',
    'Food & Personal Care Products',
    'Glass & Ceramics',
    'Insurance',
    'Inv. Banks / Inv. Cos. / Securities Cos.',
    'Jute',
    'Leasing Companies',
    'Leather & Tanneries',
    'Miscellaneous',
    'Modarabas',
    'Oil & Gas Exploration Companies',
    'Oil & Gas Marketing Companies',
    'Paper & Board',
    'Pharmaceuticals',
    'Power Generation & Distribution',
    'Real Estate Investment Trust',
    'Refinery',
    'Sugar & Allied Industries',
    'Synthetic & Rayon',
    'Technology & Communication',
    'Textile Composite',
    'Textile Spinning',
    'Textile Weaving',
    'Tobacco',
    'Transport',
    'Vanaspati & Allied Industries',
    'Woollen'
];