module.exports = [
    '3D Design Expert',
    'AC & Refrigeration Technician',
    'Accommodation Operations & Services',
    'Accountant',
    'Accounting and Book Keeping Expert',
    'Accounts Assistant',
    'Advanced Food Production',
    'Agricultural Field Assistant',
    'Air Ticketing',
    'Aluminium Fabricator',
    'Android Developer',
    'Apparel Supervisor',
    'Applied Instrumentation and Control Automation',
    'Arc and Gas Welder',
    'Area Manager',
    'Artificial Insemination Expert',
    'Auto CAD Operator',
    'Auto CAD/CAM Expert',
    'Auto Denter and Painter',
    'Auto Placket Operations Specialist',
    'Automobile Electrician',
    'Automobile Mechanic',
    'Automotive Engineer',
    'Bag Stitcher',
    'Bakery & Pastry',
    'Bakery/Pastry Expert',
    'Barista Skills (Fast Food)',
    'Beautician',
    'Beauty Therapist',
    'Bio-Medical Technician',
    'Boiler Operator',
    'Bricklaying',
    'Bridal Makeup Expert',
    'Building Draughtsman',
    'Building Electrician',
    'Building Painter',
    'Building Supervisor',
    'Butcher',
    'Button Elastic Machine Operator',
    'CAD/CAM Computerized Pattern Designing',
    'CAD/CAM Digital Embroidery Designing',
    'CAD/CAM Expert',
    'Call Center Agent',
    'Canning Expert',
    'Cardiac Assistant',
    'Carpenter',
    'Carpet Weaving Expert',
    'CCTV Camera Technician',
    'Ceramic Design',
    'Ceramics Manufacturing Expert',
    'Certificate in Retail Operations',
    'Chef',
    'Child Care Worker',
    'Circular Knitting Machine Operator',
    'Civil Draftsman (AutoCAD)',
    'Civil Draughtsman',
    'Civil Engineer',
    'Civil Lab Technician',
    'Civil Surveyor',
    'Clinical Assistant',
    'CNC Lathe Operator',
    'CNC Machine Operator',
    'CNC Programmer',
    'Computer Application',
    'Computer Application Expert',
    'Computer Business Management/IT Office Assistant',
    'Computer Graphics (Print Media)',
    'Computer Hardware Technician',
    'Computer Motion Graphic',
    'Computer Network Technician',
    'Computerized Accounting',
    'Construction Machine Operator',
    'Construction Material Technician',
    'Cook',
    'Cotton Ginning Plant Operator',
    'Crane Operator',
    'Crew Members',
    'Customer Care Service',
    'Cutting & Sewing Expert',
    'Dairy Farm Manager',
    'Dairy Herd Manager',
    'Data Entry Operator',
    'Day Care Expert',
    'Dental Assistant',
    'Dental Surgery Assistant',
    'Dies and Moulds Fitter',
    'Diesel Engine Mechanic',
    'Digital Photographer',
    'Disaster Management Expert',
    'Domestic Electrician',
    'Domestic Tailoring',
    'Domestic Worker',
    'Draftsman Mechanical AutoCAD',
    'Dress Designer',
    'Dress Maker',
    'Dress Tailor',
    'Driver',
    'E-Commerce',
    'Electric Arc Welder',
    'Electrical Appliances Servicer',
    'Electrical Welder',
    'Electrical Wireman',
    'Electricial Appliance Technician',
    'Electrician',
    'Electrician Cum PV Panel Technician',
    'Electro Medical Equipment Manager',
    'Electronic Technician',
    'Elementary Food Preservation',
    'Emergency Medical Assistant',
    'Energy Efficiency Management Supervisor',
    'Energy Efficient Compressed Air System Operator',
    'Energy Management',
    'Event Designing & Branding',
    'Event/Exhibition Organizers and Venue Operators',
    'Exhibitors',
    'Fabric Cutting Expert',
    'Fabric Designer',
    'Fabric Finishing Expert',
    'Fabric Product Development Specialist',
    'Fabric Quality Inspector',
    'Fabricator',
    'Farm Assistant',
    'Farm Manager',
    'Fashion Designer',
    'Fashion Designing',
    'Fashion Jewelry Maker',
    'Female Garments Stitcher',
    'Food and Beverage Captain',
    'Food and Beverages Management',
    'Food Processing Expert',
    'Food Production Expert',
    'Football Stitcher',
    'Footwear Designer',
    'Forging Shop Operator',
    'Garment Designer',
    'Garment Machine Operator',
    'Garment Technician',
    'Gas and Tig Welder',
    'Gas Cutter',
    'Gear Manufacturing Mechanic',
    'General Electrician',
    'General Fitter',
    'Graphic Design (Print Media)',
    'Graphic Designer',
    'Guest Relations Officer (GRO)',
    'Hair and Skin Care Specialist',
    'Hair Stylist',
    'Hair Transplant Technician- Basic',
    'Halal Butcher',
    'Hand Embroidery Expert',
    'Handicrafts Designing',
    'Hardware and Network Technician',
    'Hardware Technician',
    'Haulage Driver',
    'Health & Safety Manager',
    'Heat Treatment of Autoparts',
    'Heating Ventilation Air Conditioning and Refrigeration (HVACR)',
    'Heavy Machine Operator',
    'Home Appliance Technician',
    'Home Appliances Repair',
    'Home Textile Product Maker',
    'Hotel Management Expert',
    'House Hold Appliances Repairman',
    'House Keeping Expert',
    'HTV Operator',
    'HVACR Expert',
    'HVACR Technician',
    'Import Export Procedure and Documentation',
    'Industrial Chemistry Assistant',
    'Industrial Electrician',
    'Industrial Stitching Machine Operator',
    'Industrial Worker',
    'Industrical Stitching Machine Operator',
    'Interior Designer',
    'Interior Designing',
    'Inventory Control',
    'Jewelry Design',
    'Knitted Fabric Product Development Specialist',
    'Knitting and Embroidery Expert',
    'Knitting Machine Operator',
    'Lab Technician',
    'Land Surveyor',
    'Leather Bag & Accessories Design',
    'Leather Garment Stitcher',
    'Leather Garments Pattern Maker',
    'Leather Goods Production Expert',
    'Lift Operator',
    'Livestock Manager',
    'Loom Operator',
    'Loom Technician',
    'LTV Driver',
    'Ltv Driver',
    'Luminaire Design for Building',
    'Machine Maintenance Expert',
    'Machine Tool Operator',
    'Machinist',
    'Maintenance Technician',
    'Male Garments Cutting Expert',
    'Male Garments Stitching Expert',
    'Mason',
    'Material Evaluation & Mechanical Testing',
    'Material Lab Technician',
    'Material Technician',
    'Maternal Health Visitor',
    'Meat Handling & Processing',
    'Mechanical Draughtsman',
    'Medical Assistant',
    'Metal Worker',
    'Milling Machine Operator',
    'Millwright',
    'Mine Electrician',
    'Mobile Application Development',
    'Molding & Casting Technology',
    'Motor Winder',
    'Motor Winding Technician',
    'Motorcar Driver',
    'Motorcycle Mechanic',
    'Multi Painter',
    'Multi Welder (3GSMAW+6GGTAW)',
    'Network Professional',
    'Network Technologies',
    'Networking Technician',
    'Office Assistant',
    'Office Professional',
    'Office Secretary',
    'Operation Theater Assistant',
    'Overhead Crane Operator',
    'Packing and barcoding',
    'Pattern Designing Expert',
    'Pattern Drafting and Cutting Expert',
    'Pipe & General Fitter',
    'Pipe & Structure Fabricator',
    'Pipe and Plate Fabricator',
    'Pipe Fitter',
    'Plate Welder (X-Ray)',
    'Platter Burner',
    'PLC (Programmable Logic Control)',
    'Plc Technician',
    'Plumber',
    'Poultry Farm Manager',
    'Process Technology-Chemical Process',
    'Production Planning & Control Expert',
    'Professional Cook',
    'Quality Assurance Expert',
    'Quality Control And Assurance Expert',
    'Quality Control in Garments',
    'Quality Control Inspector in Engineering Industry',
    'Quantity Surveyor',
    'Readymade Garments Stitcher',
    'Receptionist',
    'Refractionist',
    'Restaurant Manager',
    'Safety Inspector',
    'Safety Officer',
    'Safety Supervisor',
    'Salesman',
    'Scaffolding',
    'Screen Printing',
    'Secretarial Studies',
    'Sheet Metal Die Design',
    'Ship Carpenter',
    'Ship Diesel Mechanic',
    'Ship Electrician',
    'Ship Fitter',
    'Ship Joiner Carpenter',
    'Shoe Design',
    'Shoe Designer',
    'Shoe Manufacturer',
    'Shuttering Carpenter',
    'Sock Press Man Operator',
    'Solar Photovoltaic Installation and Pumping Training',
    'Solar Photovoltaic Training',
    'Solar PV Technician',
    'Spinner/Winder/Twister',
    'Sportswear Stitcher',
    'Steel Fabricator',
    'Steel Fixer',
    'Stitching Machine Operator',
    'Surveyor',
    'Tailor',
    'Telecom Technician',
    'Telecommunication Technician',
    'Textile Designer',
    'Textile Designing',
    'Textile Dyer',
    'Textile Fitter',
    'Textile Sales & Marketing',
    'Textile Weaver',
    'Textile Wet Processing Expert',
    'Tile Fixer',
    'Tool & Die Making',
    'Tractor Mechanic',
    'Tractor Operator',
    'Traditional Dress Making & Embroidery Expert',
    'Travel Agent',
    'Turner',
    'Turner Machinist',
    'Ultrasound Technician',
    'UPS Repairman',
    'Veterinary Assistant',
    'Village Veterinary Worker',
    'Waiter',
    'Ward Manager',
    'Weaving Machine Operator',
    'Web Design and Development',
    'Web Designer',
    'Web Developer',
    'Welder',
    'Welder (SMAW/MAG/MIG/SAW)',
    'Welder (TIG & MIG)',
    'Welder/Brazer',
    'Welder/Fabricator',
    'Wireman',
    'Wood Carving Lacquer & Polishing',
    'Wood Painting and Polishing',
    'X-Ray Machine Operator',
    // New occupations
    'Helper',
    'Machine Operator',
    'Quality Inspector',
    'Sales / Marketing',
    'Recording Officer', //no
    'Rider',
    'PLC Technician',
    'Police Officer',
    'Project Manager',
    'Purchaser',
    'Quality Inspector',
    'Recovery Officer',
    'Pharmacist',
    'Store Supervisor',
    'Shop Keeper',
    'Heating Ventilation air conditioning and Refrigeration(HVACR)',
    'Teacher',
    'Guard',
    'Fitter General',
    'PLC',
    'Solar PV Installer',
    'Stall Manager',
    'Mechanic',
    'Teacher/Principal',
    'Event Organiser',
    'Librarian',
    'IT Assistant',
    'Management/HR Feild',
    'Field Officer',
    'Chemical Officer',
    'Draftsman',
    'Signal Maintainer',
    'Computer Operator',
    'Fitter',
    'Production',
    'Soldier',
    'Any job'
];